### ISSUE TITLE
Linke de redirecionamento não encontra o documento

### ISSUE THREAD

**Issue by Feppeli** [tiagovignatti/exercicios-javascript#1]
O link de redirecionamento para a lista de exercícios da rocketseat não encontra mais o documento, acredito que tenha sido trocado de endereço ou que o documento não exista mais, aguardando a resposta!

**Comment by tiagovignatti** [comment]
Peco imensa desculpa pela demora na resposta. Mas muito obrigado @Feppeli -- removi o link quebrado agora.

Se vc tiver algum conteúdo bacana com exercícios de lógica para iniciantes, eu adiciono ali (e te dou os créditos tbm 😃). Obrigado novamente!
